Version 4
SymbolType BLOCK
RECTANGLE Normal -48 -56 48 56
WINDOW 0 0 -56 Bottom 2
WINDOW 3 0 56 Top 2
SYMATTR Prefix X
SYMATTR Value NAND
SYMATTR ModelFile ltspice_cmdc0de.lib
SYMATTR SpiceModel NAND
PIN -48 -16 LEFT 8
PINATTR PinName a
PINATTR SpiceOrder 1
PIN -48 16 LEFT 8
PINATTR PinName b
PINATTR SpiceOrder 2
PIN 48 -32 RIGHT 8
PINATTR PinName y
PINATTR SpiceOrder 3
PIN 48 0 RIGHT 8
PINATTR PinName VDD
PINATTR SpiceOrder 4
PIN 48 32 RIGHT 8
PINATTR PinName GND
PINATTR SpiceOrder 5
